title: Christian Nordahl
description: Personal Website
author: Christian Nordahl
github: https://github.com/christiannordahl
about: Ph.D. Student in Computer Science at Blekinge Institute of Technology (BTH)
#location:
#  name:
#  link_name: Göteborg, Sweden
#  link: https://goo.gl/maps/ca9DpwPgx342
contact: christian.nordahl[at]bth.se
avatar_url: /static/img/Christian-Nordahl-1-cropped.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: ai ai-google-scholar ai-1.7x
      link: "https://scholar.google.se/citations?user=T7cFwBgAAAAJ&hl=en"
    - icon: fab fa-twitter
      link: "https://twitter.com/christianordahl"
    - icon: fab fa-github
      link: "https://github.com/christiannordahl"

urls:
    - text: Publications
      url: /publications

url: "https://christiannordahl.github.io"
baseurl: ""
# paginate: 20
# per_page: 20
# paginate_path: "/page/:num/"
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jemoji
  - commonmarker
  - gemoji



compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
kramdown:
    auto_ids: true
